kind = "web"
previewPath = "/"
title = "SMART CLINIC"
version = "1.0.0"
id = "artifacts/smart-clinic"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22576

[services.development]
run = "pnpm --filter @workspace/smart-clinic run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/smart-clinic", "run", "build" ]
publicDir = "artifacts/smart-clinic/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22576"
BASE_PATH = "/"
